work_dir: ./work_dir/fusion
model_saved_name: ./work_dir/fusion/fused_model
phase: train  # Set to 'train' to train fusion net, change to 'test' to evaluate
save_score: True
seed: 1
print_log: True
show_topk: [1, 5]

feeder: feeders.feeder.Feeder
num_worker: 4

train_feeder_args:
  data_path: ./dataset/volleyball_dataset/data_3/output/train_data.npy
  label_path: ./dataset/volleyball_dataset/data_3/output/train_label.pkl
  debug: False
  random_choose: True
  random_shift: True
  random_move: True
  window_size: -1
  normalization: True
  use_mmap: True

test_feeder_args:
  data_path: ./dataset/volleyball_dataset/data_3/output/test_data.npy
  label_path: ./dataset/volleyball_dataset/data_3/output/test_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: True
  use_mmap: True

spatial_model: model.zoom_new_2.Model
temporal_model: model.temporal_transformer_3.Model

spatial_weights: ./best_weight/ZT_V-SA_best_spatial.pt
temporal_weights: ./best_weight/ZT_V-SA_best_temporal.pt

model_args:
  num_class: 8
  num_person: 12
  num_point: 17
  num_head: 6
  in_channels: 3
  graph: graph.volleyball.AdjMatrixGraph
  graph_args:
    labeling_mode: 'spatial'

device: [1]
train_batch_size: 16
test_batch_size: 16
epochs: 60
lr: 0.001
