work_dir: ./work_dir/ZT_CA
model_saved_name: ./runs/ZT_CA

# feeder
feeder: feeders.feeder.Feeder
num_worker: 8
train_feeder_args:
  data_path: ./dataset/collective_dataset/train_data.npy
  label_path: ./dataset/collective_dataset/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./dataset/collective_dataset/test_data.npy
  label_path: ./dataset/collective_dataset/test_label.pkl
  normalization: False

# model
model: model.zoom_transformer_3.Model
model_args:
  num_class: 4
  num_person: 13
  num_point: 17
  num_head: 6
  in_channels: 3
  graph: graph.volleyball.AdjMatrixGraph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 0.1
step: [30, 40,50]

# training
device: [1]
batch_size: 18
test_batch_size: 18
num_epoch: 60
nesterov: True
warm_up_epoch: 2